### ISSUE TITLE
multi master transfer discussion

### ISSUE THREAD

**Issue by vincentliu84** [dpretet/axi-crossbar#5]
I have a scene when connecting 2 masters and 1 slave to crossbar,  I need to config MST1_ID_MASK = h'00  and MST2_ID_MASK = h'10,  and I see you judge the reture rch to which master based on IDs，so master 1 can only use ID: 0~15   and master 2 can only use 16 to 31.
but based on my understanding,   each master can specify different IDs and several masters can using same ID,  is this correct?

**Comment by dpretet** [comment]
Hi Vincent,

> based on my understanding, each master can specify different IDs
> 

That’s true, each master must specify  and use a unique mask ID. 

> several masters can using same ID
> 

Yes they can as long their masks are different. 

I think the testbench I provide could help understand well how to setup that, specially the MasterDriver source. Internally, the outstanding request IDs are created by a simple counter on which the mask is applied before driving the AW/AR ID signals. 

Basically what I got in mind when designing the IP was the user could create very simply the IDs by counting the ORs, then append extra MSBs (the ID mask) to the request ID. This solution provides an easy to implement circuit to drive back the completions. 

Best,
Damien

**Comment by vincentliu84** [comment]
issue is that if I set chanel 0 and channel 1 with same ID mask,   the test will hang,  if one is 0x0 and another is 0x10,  it can pass

    parameter MST0_CDC = `MST0_CDC;
    parameter MST0_OSTDREQ_NUM = `MST0_OSTDREQ_NUM;
    parameter MST0_OSTDREQ_SIZE = `MST0_OSTDREQ_SIZE;
    parameter MST0_PRIORITY = `MST0_PRIORITY;
    parameter MST0_ROUTES = 4'b1_1_1_1;
    parameter [AXI_ID_W-1:0] MST0_ID_MASK = 'h00;
    parameter MST1_CDC = `MST1_CDC;
    parameter MST1_OSTDREQ_NUM = `MST1_OSTDREQ_NUM;
    parameter MST1_OSTDREQ_SIZE = `MST1_OSTDREQ_SIZE;
    parameter MST1_PRIORITY = `MST1_PRIORITY;
    parameter MST1_ROUTES = 4'b1_1_1_1;
//    parameter [AXI_ID_W-1:0] MST1_ID_MASK = 'h10;
    parameter [AXI_ID_W-1:0] MST1_ID_MASK = 'h00;

so is there other place need to change?

**Comment by vincentliu84** [comment]
The  bready and Rready is decided on this target signal,   when channel 0 and channel 1 are setting the same mask,  
mst0_rch_targeted and mst1_rch_targeted are both 1'b1,  so ready signal will be set to channel 0
is this logic make sense?   

    assign o_rready = (mst0_rch_targeted) ? i_rready[0] :
                      (mst1_rch_targeted) ? i_rready[1] :
                      (mst2_rch_targeted) ? i_rready[2] :
                      (mst3_rch_targeted) ? i_rready[3] :
                                            1'b0;

**Comment by vincentliu84** [comment]
so if my use case is that:
master channel 0 can use ID from 0 to 31,     master 1 can also use 0 to 31,  they will access the same slave memory
how to set this ID_MASKs
Thanks

**Comment by vincentliu84** [comment]
a bug I found today is that,   when I set WID = h'10 on master 0 
both master 0 and master 1 will get bresp signals,  the master 1 vip will give an error,
the issue is due to code below:

    assign mst0_bch_targeted = ((MST0_ID_MASK & o_bch[0+:AXI_ID_W]) == MST0_ID_MASK);
    assign mst1_bch_targeted = ((MST1_ID_MASK & o_bch[0+:AXI_ID_W]) == MST1_ID_MASK);
    assign mst2_bch_targeted = ((MST2_ID_MASK & o_bch[0+:AXI_ID_W]) == MST2_ID_MASK);
    assign mst3_bch_targeted = ((MST3_ID_MASK & o_bch[0+:AXI_ID_W]) == MST3_ID_MASK);

    assign i_bvalid[0] = (mst0_bch_targeted) ? o_bvalid : 1'b0;
    assign i_bvalid[1] = (mst1_bch_targeted) ? o_bvalid : 1'b0;
    assign i_bvalid[2] = (mst2_bch_targeted) ? o_bvalid : 1'b0;
    assign i_bvalid[3] = (mst3_bch_targeted) ? o_bvalid : 1'b0;

The waveform is uploaded here:
https://github.com/vincentliu84/hello-world/blob/master/waveform3.JPG

**Comment by dpretet** [comment]
Hi Vincent,

are you sure you setup a different ID mask for both master and the AWID/ARID are correctly set according these values? That's the only reason I see without a complete wave and/or instance example that could explain this behaviour.

I tried in the doc to explain how to setup correctly the core to route the requests and their completions:

https://github.com/dpretet/axi-crossbar/blob/main/doc/architecture.md#routing-accross-the-switching-matrix

The ID mask is just extra bits to append to the AxIDs to identify correctly the master. for instance if your design needs 16 outstanding requests for both, you need 4 bits to reference them. Then you just need to append N extra bits to spot the master source. In my testcase, I use 16 OR and 0x10 for master 0, 0x20 for master 1, ..

**Comment by vincentliu84** [comment]
I just change code to this format based on my use case, and it could pass, 

    assign mst0_bch_targeted = (o_bch[0+:AXI_ID_W] >= MST0_ID_MASK) && (o_bch[0+:AXI_ID_W] <= MST0_ID_MASK+8'h0f);
    assign mst1_bch_targeted = (o_bch[0+:AXI_ID_W] >= MST1_ID_MASK) && (o_bch[0+:AXI_ID_W] <= MST1_ID_MASK+8'h0f);
    assign mst2_bch_targeted = (o_bch[0+:AXI_ID_W] >= MST2_ID_MASK) && (o_bch[0+:AXI_ID_W] <= MST2_ID_MASK+8'h0f);
    assign mst3_bch_targeted = (o_bch[0+:AXI_ID_W] >= MST3_ID_MASK) && (o_bch[0+:AXI_ID_W] <= MST3_ID_MASK+8'h0f);

**Comment by dpretet** [comment]
Vincent,

I can't help you and you don't give me more info. Please provide the instance of the core with the parameters' value and possibly a complete waveform to let me visualise the request and were the test case really fail. My test bench may be buggy, but I can use several masters, up to 4, over 1 to 4 slaves so I really suspect here a wrong configuration.

Sorry far, the code you modified is not scalable to any number of OR, I can't update the code base with such suggestion.

**Comment by vincentliu84** [comment]
> Vincent,
> 
> I can't help you and you don't give me more info. Please provide the instance of the core with the parameters' value and possibly a complete waveform to let me visualise the request and were the test case really fail. My test bench may be buggy, but I can use several masters, up to 4, over 1 to 4 slaves so I really suspect here a wrong configuration.
> 
> Sorry far, the code you modified is not scalable to any number of OR, I can't update the code base with such suggestion.

thanks,   but I see it's solved since I change the mst*_bch_targeted  
I changed my use case to:   there are 2 masters,  one ID range is 0 to 15,  another is 16 to 31,   no ID interleave now
the code is working well,
I will add more corner cases to see if I can find some other issue

**Comment by dpretet** [comment]
Ok good to you, I'm still thinking you misconfigure the core or not use the right mask for the ID request based on the few information you provided.

Be aware I'll not provide support on code you modify by your own.

**Comment by dpretet** [comment]
Something just pop up in my mind while waking up. Using a MASK_ID=0 is not allowed and most likely is the problem because it always activates the completion routing logic (0 & 4'h... = 0).

Please use a non-zero mask for your further tests, this will solve the issue. I'll add a recommendation in the doc about that and an assertion at compile time.

Damien

**Comment by vincentliu84** [comment]
> Something just pop up in my mind while waking up. Using a MASK_ID=0 is not allowed and most likely is the problem because it always activates the completion routing logic (0 & 4'h... = 0).
> 
> Please use a non-zero mask for your further tests, this will solve the issue. I'll add a recommendation in the doc about that and an assertion at compile time.
> 
> Damien

sure,  thanks for your advise, I will see if I can port my tb using your original code
