### ISSUE TITLE
Is there a porblem with the push signal of SCFIFO module？

### ISSUE THREAD

**Issue by jingzhizhang** [dpretet/axi-crossbar#7]
Data is stored when the i_awvalid is raised, but the handshake has not been successful. This will lead to duplicate data storage？

**Comment by jingzhizhang** [comment]
Sorry，I was wrong. When the fifo is not full, we can return ready to the master, which means it's ready to store data in FIFO.

**Comment by dpretet** [comment]
Hello,

You can pull or push in this FIFO whatever the empty / full flag status. The load / store will be effective only when the FIFO can send /receive a new data, this the flag will not be anymore empty or full. 

Consider that behavior as a AXI handshake. This avoids making possible dirty combinatorial loops around the control flow and make it easy to connect to an AXI channel.

Damien

**Comment by jingzhizhang** [comment]
I see. Thanks very much.
